// src/app/[locale]/layout.tsx

import type { Metadata } from "next"
import { Inter } from "next/font/google"
// 이 줄이 가장 중요합니다! 👇
import "./globals.css" // 경로가 맞는지 확인하세요.

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}