import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// locale 파라미터를 받도록 수정
export default function RootLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode
  params: {locale: string}
}) {
  return (
    // lang 속성에 locale을 전달
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}